name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-html-app .

    - name: Run Container
      run: docker run -d -p 8080:80 my-html-app

    - name: Wait for container
      run: sleep 10

    - name: Test Application
      run: curl http://localhost:8080

    - name: Deploy Step
      run: echo "Deployment successful"